# Generated by Django 5.2.1 on 2025-05-25 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('bateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.bateria')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('sucata_recebida_kg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('desconto_por_sucata', models.BooleanField(default=False)),
                ('baterias', models.ManyToManyField(through='vendas.ItemVenda', to='estoque.bateria')),
                ('servicos', models.ManyToManyField(blank=True, to='servicos.servico')),
            ],
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.venda'),
        ),
    ]
