# Generated by Django 5.2.1 on 2025-05-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INSTALACAO', 'Instalação'), ('TESTE', 'Teste de bateria'), ('LIMPEZA', 'Limpeza de polo'), ('OUTRO', 'Outro')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
