# Generated by Django 5.2.1 on 2025-06-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='tipo',
            field=models.CharField(choices=[('INSTALACAO', 'Instalação'), ('TESTE', 'Teste de bateria'), ('LIMPEZA', 'Limpeza de polo'), ('CARGA', 'Carga de bateria'), ('OUTRO', 'Outro')], max_length=20),
        ),
    ]
