# Generated by Django 5.2.1 on 2025-06-07 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('analise', 'Em análise'), ('defeito', 'Defeito'), ('troca', 'Troca fornecedor'), ('ok', 'Sem defeito')], default='analise', max_length=20)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('codigo_unico', models.CharField(max_length=100, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baterias', to='clientes.cliente')),
            ],
        ),
    ]
