# Generated by Django 5.2.1 on 2025-06-07 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_marca_delete_sucata_remove_bateria_preco_and_more'),
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='bateria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='estoque.bateria'),
        ),
    ]
