# Generated by Django 5.2.1 on 2025-05-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueSucata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
