# Generated by Django 5.2.1 on 2025-05-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucata', '0002_estoquesucata'),
        ('vendas', '0002_remove_venda_cliente_nome_itemvenda_preco_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaosucata',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_sucata', to='vendas.venda'),
        ),
    ]
